# NOTE: This workflow is overkill for most R packages
# check-standard.yaml is likely a better choice
# usethis::use_github_action("check-standard") will install it.
#
# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
      - devel
      - dev
      - ci-pipeline
  pull_request:
    branches:
      - main
      - master
      - devel
      - dev

name: docker

jobs:
  docker:
    runs-on: ubuntu-latest
    container: rocker/verse
    #or
    #container:
    #  image: ghcr.io/bczernecki/rstudio_412:latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Install thundeR dependencies
        run: R -e 'install.packages(c("climate", "aiRthermo"))'

      #- run: R CMD INSTALL ${{ github.event.repository.name }}
      - run: |
          pwd
          ls -alh
          R CMD INSTALL .
        shell: bash
      
      - name: Show installed packages
        run: Rscript -e 'installed.packages()[, 1:3]'
        shell: bash

      - name: Test coverage
        run: install.packages("covr"); covr::codecov()
        shell: Rscript {0}
