# NOTE: This workflow is overkill for most R packages
# check-standard.yaml is likely a better choice
# usethis::use_github_action("check-standard") will install it.
#
# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
      - devel
      - dev
      - ci-pipeline
  pull_request:
    branches:
      - main
      - master
      - devel
      - dev

name: docker

jobs:
  docker:
    runs-on: ubuntu-latest
    container: rocker/verse
    steps:
      - uses: actions/checkout@v1

      - run: R CMD INSTALL ${{ github.event.repository.name }}
        shell: bash
      
      - run: Rscript -e 'rmarkdown::render("report.Rmd")'

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
